#!/bin/bash
# Stage 4 on MiniMaxAI/MiniMax-M2.5 (229B FP8 MoE): adapt the converted drafter
# on the MiniMax-regenerated code split (paper Sec. 4.2).
#
#   bash examples/run_osprey_minimax_m25_adaptation.sh
#
# Required environment:
#   OSPREY_DRAFT_INIT   converted drafter directory, from
#                       scripts/osprey/convert_checkpoint.py --target minimax-m25
#   OSPREY_MINIMAX_DATA code split regenerated by MiniMax-M2.5 (JSONL)
#   OSPREY_OUTPUT       output root
#
# Optional:
#   NUM_GPUS            default 4 (the paper's single 4xB200 node). With
#                       TP_SIZE=4 that is one data-parallel replica, so the
#                       step count is num_samples * 3 / 4.
#   TP_SIZE             target tensor parallel, default 4. FP8 block size 128
#                       constrains this; 4 is the tested value.
#   LEARNING_RATE       default 1e-4
#   SGLANG_ATTN_BACKEND default flashinfer, which Blackwell needs. On Hopper
#                       fa3 is faster.
#   DRY_RUN             set to 1 to print the torchrun command only
#
# The target is served in-process by SGLang at tp=4, ep=4 to produce hidden
# states and logits on the fly; nothing is precomputed.

set -euo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ROOT_DIR=$(dirname "$SCRIPT_DIR")

export TORCHINDUCTOR_CACHE_DIR=${TORCHINDUCTOR_CACHE_DIR:-$ROOT_DIR/cache/compiled_kernels}
export SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN=1
export PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}
mkdir -p "$TORCHINDUCTOR_CACHE_DIR"

NUM_GPUS=${NUM_GPUS:-4}
TP_SIZE=${TP_SIZE:-4}
LEARNING_RATE=${LEARNING_RATE:-1e-4}
SGLANG_ATTN_BACKEND=${SGLANG_ATTN_BACKEND:-flashinfer}

for var in OSPREY_DRAFT_INIT OSPREY_MINIMAX_DATA OSPREY_OUTPUT; do
    if [ -z "${!var:-}" ]; then
        echo "ERROR: $var is not set. See the header of this script." >&2
        exit 2
    fi
done

if [ ! -d "$OSPREY_DRAFT_INIT" ]; then
    echo "ERROR: OSPREY_DRAFT_INIT is not a directory: $OSPREY_DRAFT_INIT" >&2
    echo "       Run scripts/osprey/convert_checkpoint.py --target minimax-m25 first." >&2
    exit 2
fi
if [ ! -f "$OSPREY_MINIMAX_DATA" ]; then
    echo "ERROR: missing training split: $OSPREY_MINIMAX_DATA" >&2
    exit 2
fi

echo "=== Stage 4: MiniMax-M2.5, tp=$TP_SIZE ep=4, $NUM_GPUS GPUs ==="
python "$ROOT_DIR/scripts/osprey/run_adaptation.py" \
    --target minimax-m25 \
    --draft-checkpoint "$OSPREY_DRAFT_INIT" \
    --train-data "$OSPREY_MINIMAX_DATA" \
    --output-dir "$OSPREY_OUTPUT/minimax-m25/osprey/code" \
    --cache-dir "${OSPREY_CACHE_DIR:-$ROOT_DIR/cache/osprey-minimax}" \
    --num-gpus "$NUM_GPUS" \
    --tp-size "$TP_SIZE" \
    --learning-rate "$LEARNING_RATE" \
    --sglang-attention-backend "$SGLANG_ATTN_BACKEND" \
    ${DRY_RUN:+--dry-run}
